// src/screens/MyTicketsScreen/styles.ts
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f4f7fb',
        paddingHorizontal: 0,
        paddingTop: 0,
    },
    backButton: {
        marginRight: 12,
    },
    clearButton: {
        marginLeft: 'auto',
        padding: 8,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingVertical: 16,
        paddingHorizontal: 16,
        backgroundColor: '#007AFF',
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        elevation: 6,
        marginBottom: 16,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 28,
        fontWeight: 'bold',
        letterSpacing: 0.5,
        textShadowColor: '#1565c0',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    syncInfoContainer: {
        backgroundColor: '#E3F2FD',
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginHorizontal: 16,
        marginBottom: 8,
        borderRadius: 8,
    },
    syncInfoText: {
        fontSize: 12,
        color: '#1565C0',
        textAlign: 'center',
    },
    errorContainer: {
        backgroundColor: '#FFEBEE',
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginHorizontal: 16,
        marginBottom: 8,
        borderRadius: 8,
    },
    statusContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    statusText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 16,
        lineHeight: 24,
    },
    retryButton: {
        backgroundColor: '#007AFF',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 8,
    },
    list: {
        paddingHorizontal: 18,
        paddingBottom: 32,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 18,
        marginBottom: 20,
        flexDirection: 'row',
        elevation: 4,
        shadowColor: '#1976d2',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.13,
        shadowRadius: 10,
        overflow: 'hidden',
    },
    cardImage: {
        width: 85,
        height: 85,
        borderTopLeftRadius: 18,
        borderBottomLeftRadius: 18,
        backgroundColor: '#e3eafc',
    },
    cardContent: {
        flex: 1,
        padding: 16,
        justifyContent: 'center',
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1976d2',
        marginBottom: 6,
    },
    cardDate: {
        fontSize: 15,
        color: '#607d8b',
        marginBottom: 2,
    },
    eventStatus: {
        marginTop: 4,
        fontSize: 13,
        color: '#1976d2',
        fontWeight: 'bold',
    },
    cardLocation: {
        fontSize: 14,
        color: '#90a4ae',
        fontWeight: '500',
    },
    emptyText: {
        textAlign: 'center',
        color: '#b0bec5',
        fontSize: 18,
        marginTop: 48,
    },
    errorText: {
        color: '#e53935',
        fontSize: 16,
        marginBottom: 16,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    retryText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    connectionBannerContainer: {
        width: '100%',
        alignItems: 'center',
        marginBottom: 4,
    },
    connectionBanner: {
        fontSize: 13,
        paddingHorizontal: 12,
        paddingVertical: 2,
        borderRadius: 8,
        marginTop: 4,
        opacity: 0.85,
    },
    connectionOnline: {
        backgroundColor: '#C8E6C9',
        color: '#256029',
    },
    connectionOffline: {
        backgroundColor: '#FFCDD2',
        color: '#B71C1C',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
