// src/screens/MyTicketsScreen/styles.ts
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f4f7fb',
        paddingHorizontal: 0,
        paddingTop: 0,
    },
    header: {
        paddingTop: 21,
        paddingBottom: 18,
        backgroundColor: '#1976d2',
        alignItems: 'center',
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        marginBottom: 12,
        shadowColor: '#1976d2',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 6,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 28,
        fontWeight: 'bold',
        letterSpacing: 0.5,
        textShadowColor: '#1565c0',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 8,
    },
    list: {
        paddingHorizontal: 18,
        paddingBottom: 32,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 18,
        marginBottom: 20,
        flexDirection: 'row',
        elevation: 4,
        shadowColor: '#1976d2',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.13,
        shadowRadius: 10,
        overflow: 'hidden',
    },
    cardImage: {
        width: 100,
        height: 100,
        borderTopLeftRadius: 18,
        borderBottomLeftRadius: 18,
        backgroundColor: '#e3eafc',
    },
    cardContent: {
        flex: 1,
        padding: 16,
        justifyContent: 'center',
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1976d2',
        marginBottom: 6,
    },
    cardDate: {
        fontSize: 15,
        color: '#607d8b',
        marginBottom: 2,
    },
    cardLocation: {
        fontSize: 14,
        color: '#90a4ae',
        fontWeight: '500',
    },
    emptyText: {
        textAlign: 'center',
        color: '#b0bec5',
        fontSize: 18,
        marginTop: 48,
    },
    errorText: {
        color: '#e53935',
        fontSize: 16,
        marginBottom: 16,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    retryText: {
        color: '#1976d2',
        fontSize: 16,
        marginBottom: 16,
        textAlign: 'center',
        textDecorationLine: 'underline',
        fontWeight: 'bold',
    },
});
