import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        padding: 16,
        backgroundColor: '#fff',
        alignItems: 'center',
        flex: 1,
        justifyContent: 'flex-start',
    },
    banner: {
        width: '100%',
        aspectRatio: 16 / 9,
        borderRadius: 12,
        marginBottom: 18,
        backgroundColor: '#e9e9e9',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 4,
        maxHeight: 230,
    },
    title: {
        fontSize: 26,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
        color: '#1a237e',
        letterSpacing: 0.5,
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        justifyContent: 'center',
    },
    dateText: {
        marginLeft: 8,
        color: '#555',
        fontSize: 15,
    },
    priceBox: {
        width: '100%',
        backgroundColor: '#f1f6fe',
        padding: 18,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 18,
        borderWidth: 1,
        borderColor: '#e3eafc',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
    },
    price: {
        fontSize: 22,
        fontWeight: '700',
        marginBottom: 12,
        color: '#1976d2',
    },
    counter: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e3eafc',
        borderRadius: 8,
        paddingHorizontal: 16,
        marginVertical: 10,
    },
    counterButton: {
        fontSize: 32,
        paddingHorizontal: 18,
        color: '#1976d2',
    },
    counterButtonDisabled: {
        opacity: 0.4,
    },
    counterValue: {
        fontSize: 22,
        marginHorizontal: 10,
        fontWeight: 'bold',
        color: '#222',
    },
    total: {
        fontSize: 17,
        fontWeight: '600',
        marginTop: 10,
        color: '#333',
    },
    buyButton: {
        backgroundColor: '#1976d2',
        paddingVertical: 14,
        paddingHorizontal: 28,
        borderRadius: 10,
        width: '100%',
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
        elevation: 3,
    },
    buyButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    descriptionBox: {
        width: '100%',
        backgroundColor: '#f9f9f9',
        padding: 18,
        borderRadius: 10,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: '#e3eafc',
    },
    sectionTitle: {
        fontSize: 19,
        fontWeight: 'bold',
        marginBottom: 8,
        textAlign: 'center',
        color: '#1a237e',
    },
    description: {
        fontSize: 16,
        lineHeight: 24,
        color: '#444',
        textAlign: 'center',
    },
    address: {
        textAlign: 'center',
        fontSize: 14,
        color: '#607d8b',
        marginBottom: 28,
        marginTop: 6,
        fontWeight: '500',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f6f8fc',
    },
    errorText: {
        color: '#d32f2f',
        fontSize: 16,
        fontWeight: 'bold',
    },
    root: {
        flex: 1,
        backgroundColor: '#fff',
    },
});
